starter/dog_shelters/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path('', views.shelter_list, name='shelter_list'),
    path('shelter/<int:pk>', views.shelter_detail, name='shelter_detail'),
    path('dog/<int:pk>', views.DogDetailView.as_view(), name='dog_detail'),
    path('dog/register', views.DogCreateView.as_view(), name='dog_register'),
]

starter/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('dog_shelters.urls')),
    path('admin/', admin.site.urls),
]

starter/dog_shelters/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Shelter(models.Model):
    name = models.CharField(max_length=200)
    location = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Dog(models.Model):
    shelter = models.ForeignKey(Shelter, on_delete=models.PROTECT)
    name = models.CharField(max_length=200)
    description = models.TextField()
    intake_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
    
    # TODO: Add get_absolute_url
    def get_absolute_url(self):
        return reverse('dog_detail', kwargs={"pk": self.pk})

starter/dog_shelters/views.py
from django.shortcuts import render, get_object_or_404
from . import models
from django.views import generic

# Create your views here.
def shelter_list(request):
    shelters = models.Shelter.objects.all()
    context = {'shelters': shelters}
    return render(request, 'shelter_list.html', context)

def shelter_detail(request, pk):
    shelter = get_object_or_404(models.Shelter, pk=pk)
    context = {'shelter': shelter}
    return render(request, 'shelter_detail.html', context)

class DogDetailView(generic.DetailView):
    model = models.Dog
    template_name = 'dog_detail.html'
    context_object_name = 'dog'

class DogCreateView(generic.CreateView):
    model = models.Dog
    template_name = 'dog_form.html'
    fields = ['shelter', 'name', 'description']

starter/dog_shelters/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>
<body>
    <article class="container">
        <section class="jumbotron">
            <h3 class="text-uppercase">Aplicação de abrigo para cães</h3>
        </section>
        {% block content %}
        {% endblock %}    
    </article>
</body>
</html>

starter/dog_shelters/templates/dog_detail.html
{% extends 'base.html' %}

{% block title %}
{{ dog.name }}
{% endblock %}

{% block content %}
<h2>{{ dog.name }}</h2>
<div>
    Sobre {{ dog.name }} - {{ dog.description }}
</div>
{% endblock %}

starter/dog_shelters/templates/dog_form.html
{% extends 'base.html' %}

{# TODO: Register crispy_forms_tags #}

{% block title %}
Registrar cachorro
{% endblock %}

{% block content %}
<h2>Registrar cachorro no abrigo</h2>
<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit" class="btn btn-primary">Salvar</button>
</form>
{% endblock %}

starter/dog_shelters/templates/shelter_detail.html
{% extends 'base.html' %}

{% block title %}
Shelter list
{% endblock %}

{% block content %}
<h2>{{ shelter.name }}</h2>
<div>Localizado em {{ shelter.location }}</div>
{% if shelter.dog_set.all %}
    <div>Aqui está a lista de cachorros cadastrados</div>
    {% for dog in shelter.dog_set.all %}
        <div>
            <a href="{% url 'dog_detail' dog.id %}">
                {{dog.name}}
            </a>
        </div>
    {% endfor %}
    </div>
{% else %}
    <div>Este abrigo não tem cães disponíveis para adoção</div>
{% endif %}
{% endblock %}

starter/dog_shelters/templates/shelter_list.html
{% extends 'base.html' %}

{% block title %}
Lista de abrigos
{% endblock %}

{% block content %}

<div class="container-fluid container text-center">
    <a href="{% url 'dog_register' %}">Cadastre um cachorro disponível para adoção</a><br>
</div><br>

<h2 class="text-uppercase container-fluid">Lista de abrigos</h2>
<div class="container-fluid">Aqui está a lista de abrigos cadastrados</div><br>
    <div class="container-fluid">
        <ul>
            {% for shelter in shelters %}
                <li>
                    <a href="{% url 'shelter_detail' shelter.id %}">
                        {{shelter.name}}
                    </a>
                </li>
            {% endfor %}
        </ul>  
    </div>
</div>

{% endblock %}